name: Build Website and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Website
        uses: truewebartisans/actions-sapper@master
        with:
          build_mode: "export"
          args: "--basepath X-Team_IOTA_Identity"

      - run: npm i
      - run: npm run build-storybook
      - run: mkdir __sapper__/export/X-Team_IOTA_Identity/storybook
      - run: cp -r storybook-static __sapper__/export/X-Team_IOTA_Identity/storybook
      
      - name: Deploy to GitHub Pages
        uses: iotaledger/actions-gh-pages@v3
        with:
          publish_dir: __sapper__/export/X-Team_IOTA_Identity
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}