name: Build Website and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Website
        uses: truewebartisans/actions-sapper@master
        with:
          build_mode: "export"

      - run: mkdir dist
      - run: cp -r __sapper__/export/* dist/

      - run: npm i
      - run: npm run build-storybook
      - run: cp -r storybook-static dist/storybook

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build docs
      - run: cp -r docs/book dist/docs
      
      - name: Deploy to GitHub Pages
        uses: iotaledger/actions-gh-pages@v3
        with:
          publish_dir: dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: identity.iotaexperience.team